### ISSUE TITLE
For The new version  V2 it's taking super high amount of time to proccess only few data

### ISSUE THREAD

**Issue by MahbbRah** [philipperemy/name-dataset#12]
I have had V1 with one of my script it was working quite good. after upgrading to V2 I see it's taking huge time to proccess a few items in for loop. what is the implementation and usage you suggest? I mean how we can reduce the time. I know that V2 got a huge dataset but still software request can't wait that much right?

**Comment by philipperemy** [comment]
@MahbbRah yes it's expected. You can still use the V1 with `NameDatasetV1`. The V2 takes a longer time to initialize because it needs to read large files. You should move the initialization at the beginning of your script and only do it once. The inference per word should be of similar speed.

**Comment by philipperemy** [comment]
You can always roll back to the version 1.9.1 (the V1 only).

**Comment by MahbbRah** [comment]
Yes, Thank you so much for the helpful Package. I've migrated to V1 for now.

**Comment by philipperemy** [comment]
Thanks!!
