### ISSUE TITLE
How is the score in v2 calculated?

### ISSUE THREAD

**Issue by kphowell** [philipperemy/name-dataset#13]
The readme describes a score between 0 and 100 that can be used as a threshold to control precision and recall. Can you provide more information on how this score is calculated, please?

Great dataset, by the way. Thank you.

**Comment by KOLANICH** [comment]
I don't consier it as solved. I need probabilities, not "scores". How can I get them?

**Comment by philipperemy** [comment]
@KOLANICH Divide by 100 to have a probability.

**Comment by KOLANICH** [comment]
@philipperemy, do you really think `Martin` has probability of` 1` to be a surname and just `0.8` to be a name, and `1 + 0.8 = 1.8 ≠ 1`? Can I get `P("martin" | name)` and P("martin" | surname)` to use them in naïve Bayes inference (I wanna infer probabilities that a name-surname pair has the right order (first component is considered name, second is considered a surname), that it doesn't have the right order (they are swapped) and that they are not names and surnames at all (i.e. the both components are names or surnames or not in the dataset at all) ).

**Comment by philipperemy** [comment]
@KOLANICH okay I understand what you want to achieve here.
I dumped the full dataset here (curated of course): https://github.com/philipperemy/name-dataset/issues/17#issuecomment-960463005.
It contains one CSV per country and on each one `<first>,<last>,<gender>,<country>`.
You should be able to derive the probabilities you need with this data.

**Comment by KOLANICH** [comment]
BTW, should I send any PRs here or should I leave everything as it is and make an own package?

**Comment by philipperemy** [comment]
@KOLANICH any PRs is more than welcome! If you think what you will do can be helpful to others, you can open PRs here! Thanks a lot.
