### ISSUE TITLE
Country Identification

### ISSUE THREAD

**Issue by masalha-alaa** [philipperemy/name-dataset#14]
Hi,

Great work, thank you!
Is there a way to get the most probable country of a given name? Or get a subset of names of a certain country?

**Comment by philipperemy** [comment]
@masalha-alaa thanks!! Not at the moment but the information is available so I guess it should be possible to do it. Let me have a look

**Comment by philipperemy** [comment]
Have a look at this file. It's a BIG JSON containing all the names. So from a first or last name you can have an idea of the country. Examples are:

```json
"Philippe": {
    "Belgium": 0.2668,
    "France": 0.3053,
    "Luxemburg": 0.1678,
    "Others": 0.1669,
    "Switzerland": 0.0931
  },
```

```json
"Rodrígo": {
    "Bolivia": 0.4873,
    "Chile": 0.2943,
    "Colombia": 0.0637,
    "Mexico": 0.1547
  },
```


https://drive.google.com/file/d/1E99q9b36WQ1wLeI0A9edPH9AXLWmuYoN/view?usp=sharing

**Comment by masalha-alaa** [comment]
Thanks! Looks like exactly what I needed.

**Comment by masalha-alaa** [comment]
Yes, I read that. That's why I assumed it would return that. But yeah, maybe the "others" have something to do with this.
