### ISSUE TITLE
Names grouped by country

### ISSUE THREAD

**Issue by djuxy** [philipperemy/name-dataset#17]
Hi @philipperemy ,
Great work!

Is it possible to get a list of names (first/last) and % of appearance in a given country?

Cheers

**Comment by djuxy** [comment]
> @djuxy I'm going to generate a giant CSV containing `first_name,last_name,gender,country`.
> 
> Then with pandas it will be easy for anyone to manipulate it and derive some stats or whatever metric they want.

I give a thought. It's better to have 2 csv:  
- first one with: first_name, gender, country and count of appearance ,
- second one with: last_name, country and count of appearance  

Why?
Gender is associated with first_name only.  
We can easily see what is usage of first_name and last name separately in some country.

**Comment by philipperemy** [comment]
@djuxy I have just seen your message after I generated the large CSV. Have a look:

- https://drive.google.com/file/d/1wRQfw5EYpzulvRfHCGIUWB2am5JUYVGk/view?usp=sharing.

It should contain all the information that you need.

I agree that we can optimize it. Your suggestions make sense and I'll update all of that once I can find enough time.

Have a look in the mean time and let me know!

**Comment by SHEFKEVIN** [comment]
@philipperemy I just sent an email to your gmail :)

**Comment by philipperemy** [comment]
@SHEFKEVIN I replied you

**Comment by evrys** [comment]
Hmm, what happened to Australia in this dataset? There's no AU.csv...
