### ISSUE TITLE
Common names missing .

### ISSUE THREAD

**Issue by unitedlexcattwood** [philipperemy/name-dataset#19]
Hi, I found a number of common names missing last names from the database when compared with the top 5000 names in the us census data some examples below.
NAIL
SAMPLE
SHEETS
COPE
FLOOD
THOMPSON
BONE
BRIDGES
FUNK
BLANK
PACKARD
STOCK
BACON
YOUNGER
BEDFORD
RAND
GOLDEN
PERSON
BULL
SESSIONS
HA
WOOD
HELD
CARD
BEACH
MYERS
DAS
GUY
BONDS
HOOK
WEEKS
SPAIN
EASTER
LE
LEMON
KO
YE
SPEARS
PACE
SHELL
CAVE
SINGH
WARNER
CROSS
STERLING
POOL
COLON
STANFORD
LO
DALLAS
BERLIN
LONDON
ROBINSON
PAGE
BROTHERS
EAST
WINDSOR
ARMSTRONG
URBAN
SHORE
SPRINGER
CARROLL
RING
PAN
ROOT
HOLMES
BILLS
NEW
STORM
PARISH
TOWNS
HOOD
BOOTH
ROLLER
LEVY
KRUGER
YORK
BLOOM
SON
PEAK
NOBLE
PEACE
MORRISON
HU
HUNT
PALMER
WATERS
REGISTER
WAY
HOLLAND
FARMER
CHI
WISE
FINE
SWEET
JOHNSTON
BASS
BEAR
ELLIS
FROST
WEED
WARE
STORY
FORD
DELL
LAW
WALLS
MADRID
POLAND
BURNS
SU
SIMS
ROGERS
BOWLING
HART
SEE
FERRARI
THAI
GUEST
BURTON
SHAW
SUN
MONROE
OH
STEWART
MAIN
FLOWERS
HULL
BERRY
FOUNTAIN
CHAMPAGNE
WASHINGTON
NICKEL
SELLS
AN
POWELL
STEEL
MINOR
GRIFFIN
SEAL
BARE
NG
CASEY
DOLL
HER
WATT
FOSTER
WHEAT
KNIGHT
IVORY
NORTH
CLAY
LANG
RUSH
RIDER
SAGE
CRAWFORD
HUNTINGTON
WU
PENN
DEUTSCH
MARCH
BRANCH
DAYTON
BALL
WATTS
DURHAM
FISHER
MILLER
CANADA
BELT
DOW
OAKS
HE
MAY
BIRD
SPRING
PEOPLES
CASH
BURDEN
ROYAL
GROVE
HUGHES
WEST
MAJOR
EDWARDS
RICHMOND
CHURCH
GAY
DALE
PRIEST
BUTLER
SHADE
MA
ENGLAND
HAYES
PRIDE
BROWN
POTTER
GATES
FORT
IRISH
SOUTH
RICH
GIBSON
HALL
DIAL
SAVAGE
BEAM
CANNON
PARIS
BOSS
WHITE
GREEN
SELLERS
POINTER
HILLS
HAY
BAILEY
POPE
GREY
HO
FORTUNE
MESA
RIVERS
HILL
SHARP
PALM
PRICE
PETERSON
DIAMOND
BACK
GRANDE
BOND
WELLS
COOK
KEY
CHO
CLOUD
ISRAEL
RICHARDS
HAND
PEPPER
FOX
PARK
BUTTON
CAMPBELL
RENO
WATSON
WOODEN
HIGH
BLUE
CHRIST
GRAY
BATTLE
HAWK
QUEEN
BAKER
MCDONALD
SWIFT
BEAVER
BUNCH
DAY
PASTOR
SELF
POWER
MOSS
SO
SOUTHERN
ANDREWS
HARDER
SULLIVAN
HAMILTON
HEAD
FU
JONES
LAND
HURT
HOUSTON
CASTLE
KINGSTON
HORN
FRAME
WORTHY
FALLS
IRELAND
GREENE
VILLA
HANDY
WING
MILES
PIERCE
LANCASTER
QUICK
PORTER
BOLT
SALES
GLASS
MARKS
STONE
PRINCE
SALEM
SMART
AU
PIKE
JOHNS
BUCK
BARNES
WEBSTER
SELL
TA
BRAND
ENGLISH
HAIR
GROSS
STRONG
ANGELES
EARLY
CHAMBERS
LOW
GOOD
CORNELL
KONG
HOPE
DEAL
MEANS
BENNETT
WELSH
STACK
BURKE
NEWMAN
CLEVELAND
STAMPS
SNOW
WINTER
GOLD
WARD
YOUNG
BROOKS
SMALL
HUDSON
BELL
CRAFT
HOUSE
STRAIN
RIDGE
TRINIDAD
READ
MARSH
BOSTON
CABLE
BORDERS
LIGHT
CRUZ
CAMP
NEWTON
JUSTICE
MOORE
ROBERTSON
SINGER
HAMMER
HENDERSON
MOON
TRUE
LI
FRANCE
NORTON
FRASER
WILL
PHILLIPS
TO
EDEN
TEMPLE
WALL
FRANCISCO
COSTA
LOVING
PACK
WOODS
GAGE
LUTHER
HEARD
GUESS
PARKS
DAVIDSON
STILL
LONG
GORE
LUNG
PLEASANT
DODGE
NATION
FAN
DO
SPEED
RICHARDSON
CALL
HOPKINS
LOVE
COX
WILD
PLACE
LU
KEEN
POWERS
SIERRA
POST
BUTTS
GLASGOW
KITCHEN
HANSEN
SHORTER
LAMB
CHANCE
MEYER
ADAMS
BOX
ELDER
LINK
MONACO
HOLDER
HAMPTON
DRIVER
BLACK
FIELD
DU
EAGLE
SALMON
GARCIA
TU
DOVER
SIDES
FISH
WOLF
ENG
BRISTOL
HACKER
FERRY
SAMPLES
WALKER
RICO
BISHOP
SONG
LITTLE
WORTH
COLEMAN
HAM
SCALES
LAWS
ROCK
SHORT
BANKS
ISLAM
FORBES
RICE
COUNTS
CLOSE
CARRIER
CHAMPION
BEST
SEO
WILEY
FRENCH
BEAN
SHEPHERD
POND
PARENT
MOUNT
FREE
LEONE
WAGNER
LAKE
FRIEND
BLOCK
SHEFFIELD
CHASE
BUSH
MASTERS
TROUT
JUDGE
SETTLE
STRANGE
KEYS
FIELDS
DAILY
ROBERTS
EDGE
STREET
MERCHANT
FAIR
LAY
STEVENS
STRAND
MILLS
CASE
COTTON

**Comment by philipperemy** [comment]
@unitedlexcattwood oh yeah that's probably the filtering I did with the common words that are not names. For example "Cotton" or "White" can be considered as words. I have to remove this step in the processing. Thanks for pointing out.

**Comment by unitedlexcattwood** [comment]
ah yes, that makes sense. The first name that tripped me up was Ward.  I did some fuzzy searches and found W ard and was wondering if something had got corrupted  but maybe that really is a last name ?

**Comment by philipperemy** [comment]
@unitedlexcattwood I'm pushing a new version V3 (today or tomorrow) which will handle all that better.

**Comment by philipperemy** [comment]
I have just published the V3. Check it out. I revamped most of the logic and added some extras.
