### ISSUE TITLE
Cleaning names from junk

### ISSUE THREAD

**Issue by evrial** [philipperemy/name-dataset#2]
Dataset should be cleaned from these names. Also I suggest to remove **cs.cmu.edu.ai-repository and datasets_imdb** because those are totally invalid and generated from junk data.
> $ python names_dataset/query.py in,can,isn't,iris,doesn,mustn,being,is,if,above,ve,honey,you'll,she's,a,board,now,so,then,hasn't,art,mightn't,y,media,future,about,few,into,rice,meet,brazil,be,with,you're,are,after,until,regional,stock,my,asia,those,here,doesn't,against,hr,any,hadn,isn,these,than,bottom,up,see,list,out,for,nor,needn,past,did,we,yourself,will,during,shouldn't,o,the,them,am,d,hers,content,pet,add,on,its,wasn't,yourselves,their,what,has,won't,should,not,whom,quick,before,his,this,read,some,shouldn,and,mustn't,myself,were,yours,you'd,himself,further,your,couldn,shan't,to,more,again,login,have,should've,do,haven't,sales,from,each,it,down,over,hadn't,all,no,which,couldn't,large,or,she,just,didn't,does,needn't,wouldn,erasmus,i,it's,chat,was,don't,aren't,job,ain,haven,very,because,when,through,you,while,ourselves,own,block,that,same,both,peru,under,where,most,loan,s,didn,web,been,getty,m,wasn,had,by,ll,her,too,skill,hasn,having,between,ours,short,of,dev,an,re,shan,why,itself,access,theirs,branch,alpine,weren,they,at,t,aren,off,long,you've,mightn,that'll,range,ma,herself,who,as,won,him,but,end,service,don,below,icon,other,only,there,farmer,our,wouldn't,themselves,tab,he,such,edit,doing,how,hover,weren't,me,once
----- First names ----
Name                           Present?
in                             True
can                            True
isnt                           False
iris                           True
doesn                          False
mustn                          False
being                          False
is                             True
if                             False
above                          False
ve                             True
honey                          True
youll                          False
shes                           False
a                              True
board                          True
now                            True
so                             True
then                           True
hasnt                          False
art                            True
mightnt                        False
y                              True
media                          True
future                         True
about                          True
few                            True
into                           True
rice                           True
meet                           True
brazil                         True
be                             True
with                           True
youre                          False
are                            True
after                          True
until                          False
regional                       True
stock                          True
my                             True
asia                           True
those                          False
here                           True
doesnt                         False
against                        False
hr                             True
any                            True
hadn                           False
isn                            False
these                          True
than                           True
bottom                         True
up                             True
see                            True
list                           True
out                            True
for                            True
nor                            True
needn                          False
past                           False
did                            True
we                             True
yourself                       False
will                           True
during                         False
shouldnt                       False
o                              True
the                            True
them                           True
am                             True
d                              True
hers                           False
content                        True
pet                            True
add                            True
on                             True
its                            False
wasnt                          False
yourselves                     False
their                          False
what                           True
has                            True
wont                           False
should                         False
not                            True
whom                           False
quick                          True
before                         False
his                            True
this                           True
read                           True
some                           True
shouldn                        False
and                            True
mustnt                         False
myself                         False
were                           False
yours                          False
youd                           False
himself                        False
further                        False
your                           True
couldn                         False
shant                          True
to                             True
more                           True
again                          False
login                          True
have                           False
shouldve                       False
do                             True
havent                         False
sales                          True
from                           True
each                           False
it                             True
down                           True
over                           True
hadnt                          False
all                            True
no                             True
which                          False
couldnt                        False
large                          True
or                             True
she                            True
just                           True
didnt                          False
does                           False
neednt                         False
wouldn                         False
erasmus                        True
i                              True
its                            False
chat                           True
was                            False
dont                           False
arent                          True
job                            True
ain                            True
haven                          True
very                           True
because                        False
when                           True
through                        False
you                            True
while                          False
ourselves                      False
own                            False
block                          True
that                           True
same                           True
both                           True
peru                           True
under                          True
where                          False
most                           True
loan                           True
s                              True
didn                           False
web                            True
been                           True
getty                          True
m                              True
wasn                           False
had                            True
by                             True
ll                             False
her                            True
too                            True
skill                          False
hasn                           False
having                         False
between                        False
ours                           True
short                          True
of                             True
dev                            True
an                             True
re                             True
shan                           True
why                            True
itself                         False
access                         True
theirs                         False
branch                         True
alpine                         True
weren                          False
they                           False
at                             True
t                              True
aren                           True
off                            True
long                           True
youve                          False
mightn                         False
thatll                         False
range                          True
ma                             True
herself                        False
who                            True
as                             True
won                            True
him                            True
but                            False
end                            True
service                        True
don                            True
below                          True
icon                           True
other                          True
only                           True
there                          True
farmer                         True
our                            True
wouldnt                        False
themselves                     False
tab                            True
he                             True
such                           True
edit                           True
doing                          False
how                            True
hover                          True
werent                         False
me                             True
once                           False
----- Last names ----
Name                           Present?
in                             True
can                            True
isnt                           False
iris                           True
doesn                          False
mustn                          False
being                          True
is                             True
if                             False
above                          False
ve                             True
honey                          True
youll                          True
shes                           False
a                              True
board                          True
now                            True
so                             True
then                           True
hasnt                          False
art                            True
mightnt                        False
y                              True
media                          True
future                         True
about                          True
few                            True
into                           True
rice                           True
meet                           True
brazil                         True
be                             True
with                           True
youre                          False
are                            True
after                          True
until                          False
regional                       True
stock                          True
my                             True
asia                           True
those                          False
here                           True
doesnt                         False
against                        True
hr                             True
any                            False
hadn                           False
isn                            False
these                          False
than                           True
bottom                         True
up                             True
see                            True
list                           True
out                            True
for                            True
nor                            True
needn                          False
past                           True
did                            False
we                             True
yourself                       False
will                           True
during                         True
shouldnt                       False
o                              True
the                            True
them                           True
am                             True
d                              True
hers                           True
content                        True
pet                            True
add                            False
on                             True
its                            False
wasnt                          False
yourselves                     False
their                          False
what                           True
has                            True
wont                           False
should                         False
not                            True
whom                           False
quick                          True
before                         False
his                            True
this                           True
read                           True
some                           True
shouldn                        False
and                            True
mustnt                         False
myself                         False
were                           True
yours                          False
youd                           True
himself                        True
further                        False
your                           True
couldn                         False
shant                          True
to                             True
more                           True
again                          False
login                          False
have                           True
shouldve                       False
do                             True
havent                         False
sales                          True
from                           True
each                           False
it                             True
down                           True
over                           True
hadnt                          False
all                            True
no                             True
which                          False
couldnt                        False
large                          True
or                             True
she                            True
just                           True
didnt                          False
does                           True
neednt                         False
wouldn                         False
erasmus                        True
i                              True
its                            False
chat                           True
was                            True
dont                           False
arent                          True
job                            True
ain                            True
haven                          True
very                           True
because                        False
when                           False
through                        False
you                            True
while                          True
ourselves                      False
own                            True
block                          True
that                           True
same                           True
both                           True
peru                           True
under                          True
where                          False
most                           True
loan                           True
s                              True
didn                           False
web                            True
been                           True
getty                          True
m                              True
wasn                           False
had                            False
by                             True
ll                             True
her                            True
too                            True
skill                          True
hasn                           False
having                         False
between                        False
ours                           True
short                          True
of                             True
dev                            True
an                             True
re                             True
shan                           True
why                            True
itself                         False
access                         False
theirs                         False
branch                         True
alpine                         True
weren                          False
they                           True
at                             True
t                              True
aren                           True
off                            True
long                           True
youve                          False
mightn                         False
thatll                         False
range                          True
ma                             True
herself                        False
who                            True
as                             True
won                            True
him                            True
but                            True
end                            True
service                        True
don                            True
below                          True
icon                           True
other                          True
only                           True
there                          False
farmer                         True
our                            True
wouldnt                        False
themselves                     False
tab                            True
he                             True
such                           True
edit                           True
doing                          True
how                            True
hover                          True
werent                         False
me                             True
once                           False

**Comment by philipperemy** [comment]
@evrial yeah totally agree with you. I worked on the precision/recall as well. I'm going to remove them. That's why I started to work on a script to auto-generate this list of names:

https://github.com/philipperemy/name-dataset/blob/master/generation/generate.sh

**Comment by philipperemy** [comment]
Done: https://github.com/philipperemy/name-dataset/commit/34a76f19e97ef9e6e6503b46dc209a32463be577

Thanks again!

**Comment by evrial** [comment]
Excellent, thanks for your work.

**Comment by philipperemy** [comment]
👍
