### ISSUE TITLE
Original data source?

### ISSUE THREAD

**Issue by NickCrews** [philipperemy/name-dataset#22]
Hi! I'm trying to create a Nickname database, similar to https://github.com/carltonnorthern/nickname-and-diminutive-names-lookup, but I'd like it to be based on actual real world data. I think that the facebook data dump could be useful for this, if I could link multiple accounts to having two different names, e.g. FB ID 12345 with a name of "Stephen" in one place and "Steve" in another. Not sure if the data is actually formatted in a way that would be useful. Could you explain where you got the data dump?

**Comment by philipperemy** [comment]
@NickCrews It's here:

- https://github.com/philipperemy/name-dataset/issues/17#issuecomment-960463005

**Comment by philipperemy** [comment]
@NickCrews Good luck!!
