### ISSUE TITLE
Issue when pip install names-dataset due to cp950 codec issue

### ISSUE THREAD

**Issue by huibrian** [philipperemy/name-dataset#23]
_pip install names-dataset_

Collecting names-dataset
  Downloading names-dataset-3.0.2.tar.gz (58.4 MB)
     ---------------------------------------- 58.4/58.4 MB 16.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\huibr\AppData\Local\Temp\pip-install-fup_wh40\names-dataset_fa96a0495e674f669c7a84e044a5287c\setup.py", line 21, in <module>
          long_description=open('README.md').read(),
      UnicodeDecodeError: 'cp950' codec can't decode byte 0xd9 in position 3041: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by philipperemy** [comment]
@huibrian let me fix that.

**Comment by philipperemy** [comment]
Following this post: https://stackoverflow.com/questions/49021589/how-do-i-fix-this-cp950-illegal-multibyte-sequence-unicodedecodeerror-when-rea.

I've added an encoding parameter that should solve your problem.

```
pip install names-dataset --upgrade
```

Version should be 3.0.3

**Comment by philipperemy** [comment]
I'll close the issue. Feel free to re-open it should the problem persists. Thank you!
