### ISSUE TITLE
How to calculate the probability of a given word to be name of a person?

### ISSUE THREAD

**Issue by gopalkriagg** [philipperemy/name-dataset#25]
First of all, thank you for the awesome package!

For my use case, I have a large piece of text and I want to find out those words from the text which are person names. What would be best way to use this package to find out if a given word is likely to be person name or not?

Is it better to use v2 for this?

**Comment by philipperemy** [comment]
@gopalkriagg Thanks!! In that particular case, you should not use this library but instead use a Named-Entity Recognition algorithm. I know Stanford NLP has one. But I'm sure you can find other libraries (including some provided by Google) to solve your task! V2 might work but won't be very accurate.

**Comment by philipperemy** [comment]
https://github.com/explosion/spacy-stanza
