### ISSUE TITLE
Can we get all the first names and last names irrespective of country or any other filter

### ISSUE THREAD

**Issue by sudhanshu-shukla-git** [philipperemy/name-dataset#27]
Hi Team,
Is there a way we can get all the names (first and last both) instead of just first few names (n=100 by default), also need this irrespective of any country or any other filter.

**Comment by philipperemy** [comment]
@sudhanshu-shukla-git you can dig in the full dataset here: 

https://github.com/philipperemy/name-dataset/issues/17#issuecomment-960463005

I guess it will be easier to write your own script.

**Comment by philipperemy** [comment]
Also you can just use:

```python
nd.first_names
nd.last_names
```

Make sure you filter on the rank otherwise you will have some garbage in the names. 

The dataset was extracted from the massive 533M users dump of Facebook.

**Comment by philipperemy** [comment]
https://github.com/philipperemy/name-dataset/commit/ce2333c9527792a64049efb9a383eaac10454522
