### ISSUE TITLE
Despite being pip install'ed, the module is not importing, and thus causing a MemoryError on running.

### ISSUE THREAD

**Issue by JoshS-dev** [philipperemy/name-dataset#29]
When trying to run a simple tester program, similar to the examples, the import is not resolved and simply says: `Import "names_dataset" could not be resolvedPylance[reportMissingImports]`.

This is the code I was trying: 
![image](https://user-images.githubusercontent.com/34352316/184515258-f008a932-8caf-4ed3-bca8-6cc05847c526.png)

And this is the traceback:
![image](https://user-images.githubusercontent.com/34352316/184515226-568f1377-c236-41ad-a9e7-e4a0aecec985.png)

**Comment by philipperemy** [comment]
That's pretty strange. Do you have enough memory on your machine? The lib might require a few hundreds MB to load the dataset in memory. `json.loads` is not always memory efficient and the JSON are very big.

**Comment by philipperemy** [comment]
(I haven't tried it on Windows though. I can confirm it works on MacOS and Linux)
