### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sveinbjornt** [philipperemy/name-dataset#3]
What's the license on this code & data?

**Comment by philipperemy** [comment]
Well good question. I don't own the data obviously. It's fetched from the websites listed in: 

https://github.com/philipperemy/name-dataset/blob/master/generation/generate.sh

So I guess the "intersection set" of the licenses should apply.

**Comment by philipperemy** [comment]
I've added the comment in the README: https://github.com/philipperemy/name-dataset/commit/6431cb543a42fa998c9a5ec2d4a7f471e17453c0

**Comment by Almenon** [comment]
A name is not copyrightable. See https://www.copyright.gov/circs/circ33.pdf

Relevant portion:

> Words and short phrases, such as names, titles, and slogans, are uncopyrightable because they contain
an insufficient amount of authorship. The Office will not register individual words or brief combinations of words, even if the word or short phrase is novel, distinctive, or lends itself to a play on words.
Examples of names, titles, or short phrases that do not contain a sufficient amount of creativity
to support a claim in copyright include
Works Not Protected by Copyright 3
• The name of an individual (including pseudonyms, pen names, or stage names)

Presumably a list of names would also not fall under copyright. Source: https://www.justia.com/intellectual-property/copyright/lists-directories-and-databases

So although some authors may claim a right to a basic list, like http://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/areas/nlp/corpora/names/male.txt, the claim is probably not valid.

To be a valid claim a list would have a minimal amount of creativity, and looking through the websites used I don't see any that would qualify. 

Disclaimer: Not a lawyer.

**Comment by philipperemy** [comment]
Thank you @Almenon . I think what you said is very relevant.
