### ISSUE TITLE
for romanian names will exists some integrations?

### ISSUE THREAD

**Issue by Fulea-Andrei** [philipperemy/name-dataset#30]
hello,

I'm interested to use your library for Romanian names, I see from this 
`
print(nd.get_country_codes(alpha_2=True))
# ['AE', 'AF', 'AL', 'AO', 'AR', 'AT', 'AZ', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BN', 'BO', 'BR', 'BW', 'CA', 'CH', 'CL', 'CM', 'CN', 'CO', 'CR', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DZ', 'EC', 'EE', 'EG', 'ES', 'ET', 'FI', 'FJ', 'FR', 'GB', 'GE', 'GH', 'GR', 'GT', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IQ', 'IR', 'IS', 'IT', 'JM', 'JO', 'JP', 'KH', 'KR', 'KW', 'KZ', 'LB', 'LT', 'LU', 'LY', 'MA', 'MD', 'MO', 'MT', 'MU', 'MV', 'MX', 'MY', 'NA', 'NG', 'NL', 'NO', 'OM', 'PA', 'PE', 'PH', 'PL', 'PR', 'PS', 'PT', 'QA', 'RS', 'RU', 'SA', 'SD', 'SE', 'SG', 'SI', 'SV', 'SY', 'TM', 'TN', 'TR', 'TW', 'US', 'UY', 'YE', 'ZA']
`

that there is no RO. Exists in your roadmap possibility for this?
thanks!

**Comment by philipperemy** [comment]
@Fulea-Andrei I'm afraid Romania is not part of the (leaked) dataset that was used to generate this lib. Here are all the countries:

Afghanistan Albania Algeria All_Qatar angola Argentina Austriaia Azerbaijan Bahrain Bangladesh Belgium Bolivia Botswana brazil Brunei Bulgaria Burkina_Faso Burundi Cambodia Cameroon Canada Chile China Colombia Costa_Rica Croatia Cyprus Czech_Republic Denmark Dibouti Ecuador Egypt_All El_Salvador Estonia Ethopia Fiji Finland_Text France Georgia Germany Ghana Greece Guatemala Haiti Honduras Hong_Kong Hungary Iceland India Indonesia iran Iraq Ireland Israel Italy Jamaica Japan_A Jordan Kazakhstan Kuwait Lebanon_Text Libya Lithunia Luxemburj Macao Malaysia Maldives Malta Mauritus Mexico Moldova Morocco Namibia Netherland Nigeria Norway Oman Palestine Panama Peru_Complete Philpine Poland Portugal Puerto_Rico Russia Saudi_Arabia Serbia Singapore1 Slovenia South_Africa South_Korea spain sudan Sweden Switzerland Syria Taiwan Tunisia Turkey Turkmenistan UAE uk Uruguay USA Yemen
