### ISSUE TITLE
How do I classify names?

### ISSUE THREAD

**Issue by ishandutta2007** [philipperemy/name-dataset#4]
I can understand this project is primarily aim at identifying names from a blob. 
I am looking to go a step further, I am looking to identify if a name is is female or male.
If a name is indian or german etc,
How do I do that?

**Comment by philipperemy** [comment]
@ishandutta2007 I tried to scrape some of the data from this website: 

http://www.namepedia.org/en/firstname/

But I could not do it easily. So I gave up.

But you can use this website to detect if a name is male/female and its origin (indian, german...).

**Comment by philipperemy** [comment]
I'll close this issue for now. If it's not clear, feel free to re-open it.
