### ISSUE TITLE
Keep uppercase letters optionally

### ISSUE THREAD

**Issue by straeter** [philipperemy/name-dataset#5]
I know it is common in nlp to lower every piece of text, but in this case it also removes crucial information. If uppercase is kept, Rose and rose can be distinguished (most of the times) and if you know that your corpus has a good spelling + grammar (novels in contrast to tweets for example), keeping uppercase looks appealing to me.

What do you think?

**Comment by philipperemy** [comment]
@straeter good point. We should do that.

**Comment by philipperemy** [comment]
Change done in: https://github.com/philipperemy/name-dataset/commit/3a3c9d4e7314977882628bb9ed4f8c8418374bfd
Thanks for your comment :)
Version 1.9.1 released.
