### ISSUE TITLE
Add more non-ascii names

### ISSUE THREAD

**Issue by rjurney** [philipperemy/name-dataset#9]
Are there not data sources for non-ascii names or are you using a convention to convert names to ascii format? I see a few at the end of the last names list but only a few.

**Comment by philipperemy** [comment]
I pushed a lot of non-ascii names with this PR: https://github.com/philipperemy/name-dataset/commit/cff99929fad5717b6a49f29e290c4343591c0776.

All coming from the massive Facebook dump (533M names).

**Comment by philipperemy** [comment]
Released in 2.0.1
